### ISSUE TITLE
Argument #2 ($context) must be of type array, int given

### ISSUE THREAD

**Issue by linawolf** [cobwebch/svconnector_json#12]
Upon import I get the following error:

TYPO3\CMS\Core\Log\Logger::info(): Argument #2 ($context) must be of type array, int given, called in .../vendor/cobweb/svconnector_json/Classes/Service/ConnectorJson.php on line 161

While you do test the $result for being null (line 155) the result of json_decode can be mixed, so it does not have to be an array if it is not null. It can also have a scalar value.

I would suggest to change line 155 to if (!is_array($result))  so that a proper exception is thrown if the json should return a scalar value.

**Comment by fsuter** [comment]
Sorry for not answering before. December has been awfully busy. I will look into this now.
