### ISSUE TITLE
Additional parameters for json URI

### ISSUE THREAD

**Issue by martinavk** [cobwebch/svconnector_json#4]
When using the json svconnector it would be nice to add additional parameters besides accept and user-agent. In my case I would need to add a htaccess authorization. Right now I'm using a Xclass to add this parameter, but it with a hook it would be really simple to add own parameters.

```
'connector' => 'json',
'parameters' => [
	'uri' => 'path_to_file.json',
	'authorization' => 'Basic ' . base64_encode("user:password"),
],
```

**Comment by fsuter** [comment]
Thanks for reporting your need. I have moved your request to the proper project.

**Comment by fsuter** [comment]
I propose to introduce a new "header" property, which would be an associative array, where any number of headers can be defined. This makes it totally flexible.
