### ISSUE TITLE
Argument 2 passed to Psr\Log\AbstractLogger::info() must be of the type array, null given

### ISSUE THREAD

**Issue by schi** [cobwebch/svconnector_json#8]
Sometime returned JSON data is empty. In this case fetchArray() in Cobweb\SvconnectorJson\Service\ConnectorJson throws error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 2 passed to Psr\Log\AbstractLogger::info() must be of the type array, null given, called in /var/www/html/intra/typo3conf/ext/svconnector_json/Classes/Service/ConnectorJson.php on line 141 | TypeError thrown in file /var/www/html/vendor/psr/log/Psr/Log/AbstractLogger.php in line 111.`

This can be catched by

```
        $result = json_decode($result, true);
        if (is_array($result)) {
            $this->logger->info(
                'Structured data',
                $result
            );
        } else {
            throw new \InvalidArgumentException(
                '$result "' . $result . '" must be an array.',
                1652102512
            );
        }
```

Maybe other functions need same handling.

**Comment by fsuter** [comment]
This is resolved by having `json_decode()` throw an exception if the result is not valid.
